let arr=[1,2,3,4,5,6]
console.log(arr)
console.log(arr.length)
console.log(arr[0])
arr[5]=34
console.log(arr[5])
console.log(arr[2])
console.log(arr.toString())
console.log(arr.join(" and "))
console.log(arr.pop())
console.log(arr)
console.log(arr.push(6)) 
console.log(arr) 
console.log(arr.push("vivek")) 
console.log(arr)
console.log(arr.shift())//for pop fast element
console.log(arr.unshift(34))//for add element in fast
console.log(arr)
console.log(delete arr[4])//delet an element but not remove this spece
console.log(arr)
    
arr.forEach((value , index ,arr) => {
    console.log(value, index , arr) 
});





let a1
let a3
let a2